server:
  compression:
    enabled: true
  http2:
    enabled: true
cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://www.jadersonbrancao.com.br
file:
  upload-dir: /UplodDir
spring:
  application:
    name: rest-with-spring-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 215MB
      max-file-size: 200MB
logging:
  level:
#    root: WARN
    br.com.jadersoncardoso: DEBUG
spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true